### ISSUE TITLE
Support for TYPO2 12.4

### ISSUE THREAD

**Issue by hannesbochmann** [teamneusta/pw_comments#2]
Hey, I started working on a compatible version and have already fixed several problems -> https://github.com/DMKEBUSINESSGMBH/pw_comments (branch 12.4)

Right now the extension is installable but the following tasks still need to be done:

- migrate switchableControllerActions (with the help of EXT:mktools this is a pretty easy task)
- the rendering of the plugin preview in the BE needs to be refactored
- the old controller context is used in several places which needs to be refactored
- the MailNotificationController and ProcessDatamap hook do some TypoScript parsing which maybe needs to be refactored. But only maybe because it's "only" deprecated

When those tasks are done at least the extension scanner won't find anymore problems except 4 false-positives.

**Comment by BobMali** [comment]
Hi @hannesbochmann,

thanks for your contribution!
However, it seems we have been working on the same issue. There is now a [new release](https://github.com/teamneusta/pw_comments/releases/tag/6.0.0) with full compatibility for TYPO3 v12. 
Please feel free to test it!

I am going to close the current issue, since it is resolved. If you notice any bugs or have any ideas for new features or changes please open a new issue.

Regards
